manufacturers_list = [
  {
    "FABRICANTE": "ABRACON CORPORATION",
    "ENDERECO": "501 ROOM, CRAFT BUILDING, ZHENHUA ROAD, N",
    "PAIS": "CHINA, REPÚBLICA POPULAR"
  },
  {
    "FABRICANTE": "ABRACON LLC",
    "ENDERECO": "NOVA ZELÂNDIA",
    "PAIS": "NOVA ZELÂNDIA"
  },
  {
    "FABRICANTE": "ABRACON KOREA",
    "ENDERECO": "C-223, SIGMA2, TANCHEONSANG-RO BUNDANG-G",
    "PAIS": "COREIA, REP. POP. DEMOCRÁTICA"
  },
  {
    "FABRICANTE": "ABRACON TAIWAN",
    "ENDERECO": "FORMOSA",
    "PAIS": "TAIWAN"
  },
  {
    "FABRICANTE": "AMPHENOL FCI (AFCI)",
    "ENDERECO": "BLOCK A3/A4, THE 4TH DONG KENG ROAD, GO",
    "PAIS": "CHINA, REPÚBLICA POPULAR"
  },
  {
    "FABRICANTE": "AMPHENOL",
    "ENDERECO": "5F., NO.361, FUSING 1ST RD., GUEISHAN T",
    "PAIS": "FORMOSA (TAIWAN)"
  },
  {
    "FABRICANTE": "AMPHENOL AIR LB SAS",
    "ENDERECO": "2 RUE CLEMENT ADER",
    "PAIS": "FRANÇA"
  },
  {
    "FABRICANTE": "AMPHENOL INTERCONNECT INDIA PVT. LTD.",
    "ENDERECO": "105, BHOSARI INDUSTRIAL AREA PUNE",
    "PAIS": "INDIA"
  },
  {
    "FABRICANTE": "AVX INTERNATIONAL TR",
    "ENDERECO": "Nº 9 QINGLING AVENUE YAT-SEN SCIENTIFIC",
    "PAIS": "CHINA, REPÚBLICA POPULAR"
  },
  {
    "FABRICANTE": "KYOCERA/ AVX INDUSTRIES EL SALVADOR",
    "ENDERECO": "CALLE COJUTEPEQUE EDIFICIO 4-2 ZONA FRAN",
    "PAIS": "EL SALVADOR"
  },
  {
    "FABRICANTE": "AVX CORPORATION - KYOCERA CORPORATION",
    "ENDERECO": "6 TAKEDA TOBADONO-CHO, FUSHIMI-KU",
    "PAIS": "JAPÃO"
  },
  {
    "FABRICANTE": "AVX/ KYOCERA (HK) LTD., TAIWAN BRANCH",
    "ENDERECO": "7F, NO.56, LANE 258, RUIGUANG ROAD, NEIH",
    "PAIS": "FORMOSA (TAIWAN)"
  },
  {
    "FABRICANTE": "KYOCERA AVX (USA)",
    "ENDERECO": "ONE AVX BOULEVARD, FOUNTAIN INN, SC 29644",
    "PAIS": "ESTADOS UNIDOS"
  },
  {
    "FABRICANTE": "AVX/ KYOCERA (MALAYSIA) SDN. BHD.",
    "ENDERECO": "PINTASAN KAMPUNG JAWA 1, PHASE 3 BAYAN L",
    "PAIS": "MALÁSIA"
  },
  {
    "FABRICANTE": "KYOCERA AVX COMPONENTS JERUSALEM LIMITED",
    "ENDERECO": "3 HAMARPE, JERUSALEM 9777403",
    "PAIS": "ISRAEL"
  },
  {
    "FABRICANTE": "AVX CORPORTATION CZECH REPUBLIC S.R.O",
    "ENDERECO": "DVORAKOVA 328 LANSKROUN, 563 01",
    "PAIS": "TCHECA, REPÚBLICA"
  },
  {
    "FABRICANTE": "PANASONIC CORPORATION OF CHINA",
    "ENDERECO": "5TH FLOOR, TOWER C OFFICE PARK, NO.5, JI",
    "PAIS": "CHINA, REPÚBLICA POPULAR"
  },
  {
    "FABRICANTE": "PANASONIC CORPORATION",
    "ENDERECO": "10 JALAN 6/13, SEKSYEN 6, PETALING JAYA",
    "PAIS": "MALÁSIA"
  },
  {
    "FABRICANTE": "PANASONIC - ECG (VA)",
    "ENDERECO": "8-1 UMEZU-NANKO-CHO, UKYO-KU, KYOTO-SHI",
    "PAIS": "JAPÃO"
  },
  {
    "FABRICANTE": "SAMSUNG ELECTRO-MECHANICS CO.LTD",
    "ENDERECO": "27 HEINIU CHENG-ROAD, HEXI DISTRICT",
    "PAIS": "CHINA, REPÚBLICA POPULAR"
  },
  {
    "FABRICANTE": "SAMSUNG ELETRO-MECHANICS",
    "ENDERECO": "MCKINLEY CYBERPARK, SCIENCE HUB TOWER",
    "PAIS": "FILIPINAS"
  },
  {
    "FABRICANTE": "SAMSUNG ELECTRONICS",
    "ENDERECO": "MCKINLEY CYBERPARK, SCIENCE HUB TOWER, F",
    "PAIS": "FILIPINAS"
  },
  {
    "FABRICANTE": "SAMSUNG ELECTRONICS CO. G",
    "ENDERECO": "GIHEUNG CAMPUS, 95, SAMSUNG 2-RO, GIHEUN",
    "PAIS": "COREIA, REP. POP. DEMOCRÁTICA"
  }
]
