version: "3.9"
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    restart: always
    environment:
      - ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
    command: gunicorn --reload -k eventlet -w 1 run:app --bind 0.0.0.0:5000

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
  worker:
    build: .
    # Comando para iniciar o worker.
    # OBS: Altere 'run.celery' para o caminho correto do seu objeto celery.
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A app.extensions.celery worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
    restart: always
    environment:
      - ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis