version: "3.9"
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    restart: always
    depends_on:
      - redis
      - db
    command: gunicorn --reload -k eventlet -w 1 run:app --bind 0.0.0.0:5000

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build: .
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A run_celery.celery worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
    restart: always
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
